cart/urls.py
from django.urls import path
from . import views

app_name='cart'

urlpatterns = [
    path('add/<int:product_id>/', views.add_cart, name="add_cart"),
    path('', views.cart_detail, name="cart_detail"),
    path('remove/<int:product_id>/', views.cart_remove, name="cart_remove"),
    path('remove_all/<int:product_id>/', views.remove_all, name="remove_all"),
]

core/urls.py
from django.urls import include, path
from . import views
"""kingpinlongboards URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path
app_name = 'core'

urlpatterns = [
    # path('', views.index, name='index' ),
    # path('bearings/', views.bearings, name='bearings'),
    path('', views.allProducts, name='allProducts'),
    path('<slug:c_slug>/', views.allProducts, name="products_by_category"),
    path('<slug:c_slug>/<slug:product_slug>/', views.productDetailPage, name="productDetail")
]

kingpinlongboards/urls.py
from django.urls import include, path
"""kingpinlongboards URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from core import views

urlpatterns = [
    path('', views.index, name="index"),
    path('admin/', admin.site.urls),
    path('shop/', include('core.urls', namespace='core')),
    path('search/', include('search_app.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

search_app/urls.py
from django.urls import path
from . import views

app_name="search_app"

urlpatterns = [
    path('', views.searchResult, name='searchResult'),
]

core/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField()
    image = models.ImageField(upload_to='category', blank = True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_url(self):
        return reverse('core:products_by_category', args=[self.slug])

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True) 
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='product', blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default = True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now = True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'
    
    def get_url(self):
        return reverse('core:productDetail', args=[self.category.slug, self.slug])

    def __str__(self):
        return self.name

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=100, required=True)
    last_name = forms.CharField(max_length=100, required=True)
    email = forms.EmailField(max_length=254, help_text='e.g youremail@email.com')

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'password1', 'password2')

core/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Category, Product
from django.core.paginator import Paginator, EmptyPage, InvalidPage
from django.contrib.auth.models import Group, User
from .forms import SignUpForm

# Create your views here.
def index(request):
    categories = Category.objects.all()
    return render(request, 'index.html', {"categories":categories})

def allProducts(request, c_slug=None):
    c_page = None
    products_list = None
    if c_slug!=None:
        c_page = get_object_or_404(Category, slug=c_slug)
        products_list = Product.objects.filter(category=c_page, available=True)
    else:
        products_list = Product.objects.all().filter(available=True)
        # Pagination Code
    paginator = Paginator(products_list, 6)
    try:
        page = int(request.GET.get('page','1'))
    except:
        page = 1
    try:
        products = paginator.page(page)
    except (EmptyPage, InvalidPage):
        product = paginator.page(paginator.num_pages)
    return render(request, 'category.html', {'category':c_page, 'products':products})


def productDetailPage(request, c_slug, product_slug):
    try:
        product = Product.objects.get(category__slug=c_slug, slug=product_slug)
    except Exception as e:
        raise e
    return render(request, 'product.html',{"product":product})

core/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Kingpin LongBoards-{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Nanum+Gothic" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Righteous" rel="stylesheet">
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'CSS/Core/base.css' %}" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    <script src="{% static 'JS/Core/base.js' %}"></script>
    {% block head %}
    {% endblock %}
</head>
<body>
    <nav class="topNav row" id="myTopNav">
        <ul class="dropdownNavList">
            <div class="navDiv">
                <a href="{% url 'index' %}" class="col-3" id="branding">
                    <li>
                        <i class="fas fa-home"></i> Kingpin Longboards
                    </li>
                </a>
            </div>
            {% if item_count > 0 %}
            <div class="dropdown col-3">
                    <button class="dropbtn">Browse by category
                        <i class="fa fa-caret-down"></i>
                    </button>
                    <div class="dropdown-content">
                        {% for category in links %}
                            <li class="dropdownLink"><a href="{{category.get_url}}">{{category.name}}</a></li>
                        {% endfor %}
                    </div>
                </div>
                <form action="{% url 'search_app:searchResult' %}" method="get" class="col-5">
                    {% csrf_token %}
                    <input type="search" placeholder="Search" aria-label="Search" name="q" id="searchInput">
                    <button type="submit" id="searchButton">Search</button>
                </form>
                <a href="{% url 'cart:cart_detail' %}" class="col-1 shoppingCart"><li><i class="fas fa-shopping-cart"></i></li>({{item_count}})</a>
            {% else %}
                <div class="dropdown col-4">
                    <button class="dropbtn">Browse by category
                        <i class="fa fa-caret-down"></i>
                    </button>
                    <div class="dropdown-content">
                        {% for category in links %}
                            <li class="dropdownLink"><a href="{{category.get_url}}">{{category.name}}</a></li>
                        {% endfor %}
                    </div>
                </div>
                <form action="{% url 'search_app:searchResult' %}" method="get" class="col-5">
                    {% csrf_token %}
                    <input type="search" placeholder="Search" aria-label="Search" name="q" id="searchInput">
                    <button type="submit" id="searchButton">Search</button>
                </form>
            {% endif %}
            <a href="javascript:void(0);" class="icon" id="hamburgerIcon">&#9776;</a>
        </ul>
    </nav>
    {% block content %}
    {% endblock %}    
</body>
</html>

core/templates/bearings.html
{% extends 'base.html' %}
{% load staticfiles%}
<!DOCTYPE html>
<html>
<head>
    {% block head %}
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}Bearings{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% comment %} <link rel="stylesheet" type="text/css" media="screen" href="main.css" />
    <script src="main.js"></script> {% endcomment %}
    {% endblock %}
</head>
<body>
    {% block content %}
        {% for bearing in bearings  %}
            <header>{{bearing.name}}</header>
        {% endfor %}    
    {% endblock %}
</body>
</html>

    

core/templates/category.html
{% extends 'base.html' %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    {% block head %}
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{% block title %}{% if category %} {{ category.name }}{% endif %}{% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css" media="screen" href="{% static 'CSS/Core/category.css'%}" />
        <script src="main.js"></script>
    {% endblock %}
</head>
<body>
    {% block content %}
        {% if category  %}
            <div>
                <div>
                    <p class="allProductsLinkParagraph"><a href="{% url 'core:allProducts' %}" class="allProductsLink">View All Products</a> | {{category.name}}</p>
                </div>
            </div>
        {% endif %} 
        <div class="row topCategoryDiv">
        {% if category %}
            <img src="{{category.image.url}}" alt="{{ category.name }}" class="col-12 singleCategoryImage">
        </div>
        {% else %}
            <div class="row">
                <p class="col-12" id="allProductsHeader">All Products</p>
            </div>
            <img src="{% static 'images/allProducts.jpg'%}" alt="all products image" class="col-12">
        </div>
        {% endif %}
        <div>
            <div>
                <div class="row productRow">
                {% for product in products.object_list %}
                        <div class="productDiv col-4">
                            <a href="{{product.get_url}}"><img src="{{product.image.url}}" alt="{product.name}" class="productImage"></a>
                            <div class="productNamePrice">
                                <h4 class="productName">{{product.name}}</h4>
                                <p class="productPrice">${{product.price}}</p>
                            </div>
                        </div>
                        {% if forloop.counter|divisibleby:3 %}
                            </div><div class="row">
                        {% endif %}
                {% endfor %}
            </div>
            </div>
            <div class="mx-auto">
                
                {% if products.paginator.num_pages > 1  %}
                    <hr>
                    <div>
                        
                        {% for pg in products.paginator.page_range  %}
                            <a href="?page={{pg}}" class="{% if products.number == pg %}active{% endif %}">
                                {{pg}}
                            </a>
                        {% endfor %}
                            
                    </div>
                {% endif %}      
            </div>
        </div>   
    {% endblock %}
</body>
</html>

core/templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    {% block head %}
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}Home{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'CSS/Core/index.css' %}" />
    {% comment %}<script src="main.js"></script> {% endcomment %}
    {% endblock %}
</head>
<body>
    {% block content %}  
    <div class="row">
        <h1 class="categoryPageHeading col-12">Product Categories</h1>
    </div>
    <div class="row">
        {% for category in categories %}
            <a href="{{category.get_url}}" class="col-6 homePageCategoryLink">
                <div style="background-image:url({{category.image.url}})" class="homePageCategoryDiv">
                    <div><h2 class="homePageCategoryHeader">{{category.name}}</h2></div>
                    <p class="homePageCategoryDescription">{{category.description}}</p>
                </div>
            </a>
            {% if forloop.counter|divisibleby:2 %}
                </div><div class="row">
            {% endif %}
        {% endfor %} 
    </div>
    {% endblock  %} 
</body>
</html>

core/templates/product.html
{% extends "base.html" %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
    {% block head %}
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{% block title %}Page Title{% endblock title %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css" media="screen" href="{% static 'CSS/Core/product.css' %}" />
        <script src="main.js"></script>
    {% endblock head %}
</head>
<body>
    {% block content %}
        <div>
            <div>
                <div class="row">
                    <p class="productPageLink col-12"><a href="{% url 'index' %}" class="topLinks">Home</a> | <a href="{{ product.category.get_url }}" class="topLinks">{{ product.category }}</a> | {{product.name}}</p>
                </div>
                <div class="row singleProductDiv">
                    <div class="imageDiv col-8">
                        <img src="{{product.image.url}}" alt="{{product.name}}" class="productImage">
                    </div>
                    <div class="infoDiv col-4">
                        <h1 class="productInfo productName">{{ product.name }}</h1>
                        <p class="productInfo productPrice">${{product.price}}</p>
                        <p class="productInfo productDescription">{{product.description}}</p>
                        {% if product.stock <= 0 %}
                            <p>Out of Stock</p>
                        {% else %}
                            <a href="{% url 'cart:add_cart' product.id %}" class="productInfo addToCartLink">Add to Cart</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    {% endblock content %}  
</body>
</html>