cart/urls.py
from django.urls import path
from . import views

app_name='cart'

urlpatterns = [
    path('add/<int:product_id>/', views.add_cart, name="add_cart"),
    path('', views.cart_detail, name="cart_detail"),
    path('remove/<int:product_id>/', views.cart_remove, name="cart_remove"),
    path('remove_all/<int:product_id>/', views.remove_all, name="remove_all"),
]

core/urls.py
from django.urls import include, path
from . import views
"""kingpinlongboards URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path
app_name = 'core'

urlpatterns = [
    # path('', views.index, name='index' ),
    # path('bearings/', views.bearings, name='bearings'),
    path('', views.allProducts, name='allProducts'),
    path('<slug:c_slug>/', views.allProducts, name="products_by_category"),
    path('<slug:c_slug>/<slug:product_slug>/', views.productDetailPage, name="productDetail")
]

kingpinlongboards/urls.py
from django.urls import include, path
"""kingpinlongboards URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from core import views

urlpatterns = [
    path('', views.index, name="index"),
    path('admin/', admin.site.urls),
    path('shop/', include('core.urls', namespace='core')),
    path('search/', include('search_app.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models
from core.models import Product

# Create your models here.
class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)
    class Meta:
        db_table='Cart'
        ordering = ['date_added']
    
    def __str__(self):
        return self.cart_id

class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)
    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        return self.product.price *self.quantity

    def __str__(self):
        return self.product 

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from core.models import Product
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist
import stripe
from django.conf import settings
from order.models import Order, OrderItem


# Create your views here.
def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart

def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(cart_id=_cart_id(request))
        cart.save()
    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        if cart_item.quantity <= cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
                product = product,
                quantity = 1,
                cart = cart
            )
        cart_item.save()
    return redirect('cart:cart_detail')

def cart_detail(request, total=0, counter=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    stripe.api_key = settings.STRIPE_SECRET_KEY
    stripe_total = int(total*100)
    description = "Kingpin Longboards - New Order"
    data_key = settings.STRIPE_PUBLISHABLE_KEY
    if request.method == 'POST':
        print(request.POST)
        try:
            token = request.POST['stripeToken']
            email = request.POST['stripeEmail']
            billingName = request.POST['stripeBillingName']
            billingAddress1 = request.POST['stripeBillingAddressLine1']
            billingcity = request.POST['stripeBillingAddressCity']
            billingPostcode = request.POST['stripeBillingAddressZip']
            billingCountry = request.POST["stripeBillingAddressCountryCode"]
            shippingName=request.POST['stripeShippingName']
            shippingAddress1 = request.POST["stripeShippingAddressLine1"]
            shippingcity = request.POST['stripeShippingAddressCity']
            shippingPostcode = request.POST['stripeShippingAddressZip']
            shippingCountry = request.POST['stripeShippingAddressCountryCode']
            customer = stripe.Customer.create(
                email=email,
                source=token
            )
            charge = stripe.Charge.create(
                amount=stripe_total,
                currency="usd",
                description=description,
                customer=customer.id
            )

        
            # Creating the order
            try:
                order_details = Order.objects.create(
                    token=token,
                    total=total,
                    email = email,
                    billingName = billingName,
                    billingAddress1 = billingAddress1,
                    billingCity = billingcity,
                    billingPostcode = billingPostcode,
                    billingCountry = billingCountry,
                    shippingName = shippingName,
                    shippingAddress1 = shippingAddress1,
                    shippingCity = shippingcity,
                    shippingPostcode = shippingPostcode,
                    shippingCountry = shippingCountry
                )
                order_details.save()
                for order_item in cart_items:
                    oi = OrderItem.objects.create(
                        product = order_item.product.name,
                        quantity = order_item.quantity,
                        price = order_item.product.price,
                        order = order_details
                    )
                    oi.save()
                    # reduce stock when order is placed or saved.
                    products = Product.objects.get(id=order_item.product.id)
                    products.stock = int(order_item.product.stock - order_item.quantity)
                    products.save()
                    order_item.delete()
                return redirect('order:thanks', order_details.id)
            except ObjectDoesNotExist:
                pass
        except stripe.error.CardError as e:
            return False, e
    return render(request, "cart.html", dict(cart_items=cart_items, total = total, counter = counter, data_key = data_key, stripe_total = stripe_total, description = description))

def cart_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -=1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')

def remove_all(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

cart/templates/cart.html
{% extends "base.html" %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    {% block head %}
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{% block title %}Page Title{% endblock title %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css" media="screen" href="{% static 'CSS/Core/cart.css' %}" />
        <script src="main.js"></script>  
    {% endblock head %}
</head>
<body>
    {% block content %}
        {% if not cart_items %}
          <div class="row">
              <div class="col-10 cartIsEmpty">
                    <h1 class="pageText">Your shopping cart is empty</h1>
                    <p class="pageText">Please click <a href="{% url 'core:allProducts' %}">here</a> to continue shopping</p>  
              </div>
          </div>
        {% else %}
        <div class="row">
            <h1 class="col-12 yourShoppingCart pageText yourShoppingCart">Your Shopping Cart</h1>
        </div>
            <div>
                <div class="row">
                    <h2 class="col-12 itemsHeader pageText">Items</h2>
                </div>
                    {% for cart_item in cart_items  %}
                        <div class="row productDiv">
                            <div>
                                <a href="cart_item.product.get_absolute_url"><img src="{{cart_item.product.image.url}}" alt="" class="col-5 checkoutProductImage"></a>
                            </div>
                            <div class="col-5 infoDiv">
                                <p class="pageText checkoutInfo">{{ cart_item.product.name}}</p>
                                <br>
                                <p class="pageText checkoutInfo">SKU: {{cart_item.product.id}}</p>
                                <br>
                                <p class="pageText checkoutInfo">Unit Price: ${{cart_item.product.price}}</p>
                                <br>
                                <p class="pageText checkoutInfo">Qty: {{cart_item.quantity}} x ${{cart_item.product.price}}</p>
                                <br>
                                <p class="pageText checkoutInfo">Subtotal: ${{cart_item.sub_total}}</p>
                            </div>  
                            {% if cart_item.quantity < cart_item.product.stock %}
                                    <div class="cartButtonRow col-2">
                                        <a href="{% url 'cart:add_cart' cart_item.product.id %}"><i class="fas fa-plus-circle cartPageIcons checkoutInfo"></i></a>&nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}"><i class="fas fa-minus-circle cartPageIcons checkoutInfo"></i></a>&nbsp;<a href="{% url 'cart:remove_all' cart_item.product.id %}"><i class="fas fa-trash-alt cartPageIcons checkoutInfo"></i></a>
                                    </div>
                                {% else %}
                                    <div class="cartButtonRow col-2">
                                        <a href="{% url 'cart:cart_remove' cart_item.product.id %}"><i class="fas fa-minus-circle cartPageIcons checkoutInfo"></i></a>&nbsp;<a href="{% url 'cart:remove_all' cart_item.product.id %}"><i class="fas fa-trash-alt cartPageIcons checkoutInfo"></i></a>
                                    </div>
                                {% endif %}
                            </div>  
                    {% endfor %} 
                <div class="checkoutDiv">
                    <div class="checkoutDiv row">
                        <h2 class="col-12 pageText checkoutTitle">Checkout</h2>
                    </div>
                    <div class="reviewYourCartDiv row">
                        <p class="col-12 pageText">Please review your shopping cart before proceeding with payment</p>
                    </div>
                    <div class="yourTotal row">
                        <p class="col-12 pageText">Your total is  <strong>${{ total }}</strong></p>
                    </div>
                    <div class="stripeButton row">
                        <div class="col-12">
                        <form action="" method="POST" class="stripeButton">
                            {% csrf_token %}
                            <script
                            src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                            data-key="{{data_key}}"
                            data-amount="{{stripe_total}}"
                            data-name="Kingpin Longboards"
                            data-description="{{ description }}"
                            data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
                            data-locale="auto"
                            data-currency="usd"
                            data-shipping-address="true"
                            data-billing-address="true"
                            data-zip-code="true">
                            </script>
                        </form>
                        <span class="pageText">or</span>
                        <a href="{% url 'core:allProducts' %}" class="continueShopping pageText">Continue Shopping</a>
                    </div>
                </div>
            </div>
      {% endif %}
    {% endblock content %}
</body>
</html>